server {
  listen 80;
  server_name localhost;

  # Tells Nginx where your built files live
  # index.html is the default file to serve
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri /index.html;
  }
}